build_runtime_centos:
  image: registry.gitlab.com/gbraad/fedora:24
  script:
    - dnf install -y git make sudo rpm-ostree flatpak
    - git clone https://gitlab.com/gbraad/flatpak-centos-runtime.git src --depth 1
    - cd src
    - make
  artifacts:
    paths:
      - src/exportrepo/

build_runtime_opensuse:
  image: registry.gitlab.com/gbraad/opensuse:42.1
  script:
    - zypper install -y git make sudo ostree flatpak
    - zypper ar -f http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_42.1/Virtualization:Appliances:Builder.repo
    - zypper --no-gpg-checks install -y python3-kiwi
    - git clone https://gitlab.com/gbraad/flatpak-opensuse-runtime.git src --depth 1
    - cd src
    - make
