stages:
  - prepare
  - build

build_base:
  stage: prepare
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/flatpak-runtime-build:latest .
    - docker push registry.gitlab.com/gbraad/flatpak-runtime-build:latest
  only:
    - master

build_runtime_freedesktop:
  stage: build
  image: registry.gitlab.com/gbraad/flatpak-runtime-build
  script:
    - git clone https://github.com/flatpak/freedesktop-sdk-images.git src --depth 1
    - cd src
    - make REPO=exportrepo
  artifacts:
    paths:
      - src/exportrepo

build_runtime_gnome:
  stage: build
  image: registry.gitlab.com/gbraad/flatpak-builder-freedesktop
  script:
    - git clone https://git.gnome.org/browse/gnome-sdk-images src --depth 1
    - cd src
    - make REPO=exportrepo
  artifacts:
    paths:
      - src/exportrepo

build_runtime_centos:
  stage: build
  image: registry.gitlab.com/gbraad/flatpak-runtime-build
  script:
    - dnf install -y git make sudo rpm-ostree flatpak
    - git clone https://gitlab.com/gbraad/flatpak-centos-runtime.git src --depth 1
    - cd src
    - make
  artifacts:
    paths:
      - src/exportrepo/

build_runtime_opensuse:
  stage: build
  image: registry.gitlab.com/gbraad/opensuse:42.1
  script:
    - zypper install -y git make sudo
    - zypper addrepo -f http://download.opensuse.org/repositories/Virtualization:/Appliances:/Builder/openSUSE_Leap_42.1/Virtualization:Appliances:Builder.repo
    - zypper --no-gpg-checks install -y python3-kiwi
    - zypper addrepo http://download.opensuse.org/repositories/home:fcrozat:branches:openSUSE:Leap:42.1:Update/standard/home:fcrozat:branches:openSUSE:Leap:42.1:Update.repo
    - zypper --no-gpg-checks install -y flatpak
    - git clone https://gitlab.com/gbraad/flatpak-opensuse-runtime.git src --depth 1
    - cd src
    - make
  artifacts:
    paths:
      - src/exportrepo/